name = "Aeronautically Optimized"
author = "Looney"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0afa993204aa0764c834d2668784c1fc18459066d1bb2228debc767754f7818"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
