name = "Aeronautically Optimized"
author = "Looney"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06fb690c648e0d3b106c85daf5cb4b37c604f528cbd18af185e993974002796a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
