name = "Aeronautically Optimized"
author = "Looney"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be9e47ef1dc5a5e49f38cb0e901f59f7536b115ed6211abce59ee325bce17be8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
